"""Tests for the Markdown → Telegram-HTML helper.

We rely on this for safe rendering of LLM output, so the escape behaviour
matters: angle brackets in user text must be escaped, but the same
characters generated by our own bold/italic/code conversions must not.
"""

from bot.formatting import md_to_telegram_html


def test_empty_returns_empty():
    assert md_to_telegram_html("") == ""


def test_bold_and_italic():
    assert "<b>x</b>" in md_to_telegram_html("**x**")
    assert "<i>x</i>" in md_to_telegram_html("*x*")


def test_inline_code_escapes_html():
    out = md_to_telegram_html("`<script>`")
    assert "<code>&lt;script&gt;</code>" in out


def test_code_block():
    out = md_to_telegram_html("```py\nprint(1)\n```")
    assert "<pre>print(1)\n</pre>" in out


def test_link():
    out = md_to_telegram_html("[Dograh](https://dograh.com)")
    assert '<a href="https://dograh.com">Dograh</a>' in out


def test_outside_code_html_is_escaped():
    out = md_to_telegram_html("hello <world>")
    assert "hello &lt;world&gt;" in out
