"""Voice-note transcription via Groq Whisper.

Adapted from CliClaw's voice.py — STT only. TTS reply is generated by
the Dograh workflow run and emitted as a Telegram voice note in Phase 5
(needs the chat-with-run streaming wired then). See ADR-101.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Optional

import httpx
from aiogram import Bot
from aiogram.types import Voice
from loguru import logger


_GROQ_URL = "https://api.groq.com/openai/v1/audio/transcriptions"
_WHISPER_MODEL = "whisper-large-v3-turbo"


async def transcribe_voice(
    voice: Voice, bot: Bot, groq_api_key: str
) -> Optional[str]:
    """Download a Telegram voice message and STT it via Groq Whisper.

    Returns the transcript, an error sentinel string, or ``None`` if the
    Groq API key isn't configured.
    """
    if not groq_api_key:
        return None

    tmp_path: Optional[Path] = None
    try:
        file = await bot.get_file(voice.file_id)
        tmp_path = (
            Path(tempfile.gettempdir()) / f"dograh_voice_{voice.file_id}.ogg"
        )
        await bot.download_file(file.file_path, destination=str(tmp_path))

        async with httpx.AsyncClient(timeout=60.0) as client:
            with open(tmp_path, "rb") as fh:
                resp = await client.post(
                    _GROQ_URL,
                    headers={"Authorization": f"Bearer {groq_api_key}"},
                    files={"file": (tmp_path.name, fh, "audio/ogg")},
                    data={"model": _WHISPER_MODEL, "response_format": "json"},
                )
        if resp.status_code != 200:
            logger.warning(
                f"[voice] Groq STT returned {resp.status_code}: "
                f"{resp.text[:200]}"
            )
            return f"[STT error {resp.status_code}]"
        return resp.json().get("text", "").strip()
    except Exception as exc:  # noqa: BLE001
        logger.exception(f"[voice] transcribe failed: {exc!r}")
        return f"[STT error: {type(exc).__name__}]"
    finally:
        if tmp_path is not None and tmp_path.exists():
            try:
                tmp_path.unlink()
            except OSError:
                pass
